### ISSUE TITLE
Items still not charging

### ISSUE THREAD

**Issue by ghost** [J3fftw1/LiteXpansion#23] opened 2020-07-04 18:16 UTC
I'm sorry to say this again, but the nano blade, the electric chestplate and the food synthesizer are still not charging. I tried every version that goes from 37 to 40 but nothing.

**Comment by WalshyDev** [comment] 2020-07-04 18:19
Send all versions

**Comment by ghost** [comment] 2020-07-05 13:34
> Send all versions

[INFO] ....>.... Paper v1_16_R1

[INFO] ....

[INFO] .... CS-CoreLib vDEV - 88 (git 6a39a9e7)

[INFO] .... Slimefun vDEV - 576 (git ee7fb238)

[INFO] .... Backwards compatiblity enabled!

[INFO] ....

[INFO] .... Installed Addons (5)

[INFO] .... Barrels vDEV - 11 (git abecba9c)

[INFO] .... LiteXpansion vDEV - 42 (git 2df1e3bf)

[INFO] .... SoulJars vDEV - 16 (git 36dce719)

[INFO] .... HotbarPets vDEV - 28 (git 89eb962c)

[INFO] .... ExoticGarden vDEV - 54 (git 304c3908)

**Comment by NeoMystical** [comment] 2020-07-07 03:47
it not charge and lost this charging bench when put items on it 
Slimefun,Cs-corelib,LiteExpansion are Lastest version on 7 July 2020

[10:43:18] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SuperLobby v3.1.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2133) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
        at com.pedrojm96.superlobby.listener.PlayerE.MenuClick(PlayerE.java:99) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        ... 17 more
[10:43:19] [Server thread/WARN]: [Slimefun]
[10:43:19] [Server thread/WARN]: [Slimefun] An Error occurred! It has been saved as:
[10:43:19] [Server thread/WARN]: [Slimefun] /plugins/Slimefun/error-reports/2020-07-07-10-43 (1).err
[10:43:19] [Server thread/WARN]: [Slimefun] Please put this file on https://pastebin.com and report this to the developer(s).
[10:43:19] [Server thread/WARN]: [Slimefun] Bug Tracker: https://github.com/TheBusyBiscuit/Slimefun4/issues
[10:43:19] [Server thread/WARN]: [Slimefun]
[10:43:20] [Craft Scheduler Thread - 14/ERROR]: [Slimefun] X: -262 Y: 67 Z: 85 (CHARGING_BENCH)
[10:43:20] [Craft Scheduler Thread - 14/ERROR]: [Slimefun] has thrown 4 error messages in the last 4 Ticks, the Block has been terminated.
[10:43:20] [Craft Scheduler Thread - 14/ERROR]: [Slimefun] Check your /plugins/Slimefun/error-reports/ folder for details.
[10:43:20] [Craft Scheduler Thread - 14/ERROR]: [Slimefun]

**Comment by J3fftw1** [comment] 2020-07-13 12:59
should be fixed now try updating

**Closed as completed** 2020-07-13 15:43 UTC
