### ISSUE TITLE
Electric Chestplates do not negate damage

### ISSUE THREAD

**Issue by NCBPFluffyBear** [J3fftw1/LiteXpansion#35] opened 2020-08-15 16:47 UTC
## Description (REQUIRED)
The electric chestplate does not negate damage dealt to the player. LX thinks the chestplate has no charge. (I know this was reported already, I'm going to include a console error)

## Steps to reproduce the Issue (REQUIRED)
1. Obtain an electric chestplate
2. Charge the electric chestplate
3. Get hit by a mob or take fall damage (easier to reproduce)

## Expected behavior (REQUIRED)
The charge of the electric chestplate should decrease, the durability should not decrease when charged, and the player should not take any damage.

## Server Log
https://pastebin.com/qMpKJtmx

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft version: 1.16.1
 - CS-CoreLib version: CS-CoreLib vDEV - 88 (git 6a39a9e7)
 - Slimefun version: Slimefun vDEV - 630 (git 8b02c18b)
 - LiteXpansion version: LiteXpansion vDEV - 52 (git 3acb52b)

**Comment by WalshyDev** [comment] 2020-08-15 22:08
Duplicate of #28

**Closed as completed by WalshyDev** 2020-08-15 22:08 UTC
Labels: bug
